config/routes.rb
Rails.application.routes.draw do
  resources :architectures
  resources :deployments
  resources :load_balancers
  resources :servers
  resources :forms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'forms#new'
end

app/models/architecture.rb
class Architecture < ApplicationRecord
  belongs_to(:form, required: false)
end

app/controllers/architectures_controller.rb
class ArchitecturesController < ApplicationController
  before_action :set_architecture, only: [:show, :edit, :update, :destroy]

  # GET /architectures
  # GET /architectures.json
  def index
    @architectures = Architecture.all
  end

  # GET /architectures/1
  # GET /architectures/1.json
  def show
  end

  # GET /architectures/new
  def new
    @architecture = Architecture.new
  end

  # GET /architectures/1/edit
  def edit
  end

  # POST /architectures
  # POST /architectures.json
  def create
    @architecture = Architecture.new(architecture_params)

    respond_to do |format|
      if @architecture.save
        format.html { redirect_to @architecture, notice: 'Architecture was successfully created.' }
        format.json { render :show, status: :created, location: @architecture }
      else
        format.html { render :new }
        format.json { render json: @architecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /architectures/1
  # PATCH/PUT /architectures/1.json
  def update
    respond_to do |format|
      if @architecture.update(architecture_params)
        format.html { redirect_to @architecture, notice: 'Architecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @architecture }
      else
        format.html { render :edit }
        format.json { render json: @architecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /architectures/1
  # DELETE /architectures/1.json
  def destroy
    @architecture.destroy
    respond_to do |format|
      format.html { redirect_to architectures_url, notice: 'Architecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_architecture
      @architecture = Architecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def architecture_params
      params.require(:architecture).permit(:description, :diagram_file_name, :diagram_content_type, :diagram_file_size, :diagram_updated_at)
    end
end

app/helpers/architectures_helper.rb
module ArchitecturesHelper
end

app/views/architectures/_form.html.erb
<%= form_for(architecture) do |f| %>
  <% if architecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(architecture.errors.count, "error") %> prohibited this architecture from being saved:</h2>

      <ul>
      <% architecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.file_field(:diagram, class: "btn btn-default btn-file") %>
  </div>

  <div class="field">
    <%= f.label :form_id %>
    <%= f.text_field :form_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/architectures/edit.html.erb
<h1>Editing Architecture</h1>

<%= render 'form', architecture: @architecture %>

<%= link_to 'Show', @architecture %> |
<%= link_to 'Back', architectures_path %>

app/views/architectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Architectures</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Diagram</th>
      <th>Form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @architectures.each do |architecture| %>
      <tr>
        <td><%= architecture.description %></td>
        <td><%= architecture.diagram_file_name %></td>
        <td><%= link_to 'Show', architecture %></td>
        <td><%= link_to 'Edit', edit_architecture_path(architecture) %></td>
        <td><%= link_to 'Destroy', architecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Architecture', new_architecture_path %>

app/views/architectures/new.html.erb
<h1>New Architecture</h1>

<%= render 'form', architecture: @architecture %>

<%= link_to 'Back', architectures_path %>

app/views/architectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @architecture.description %>
</p>



<p>
  <strong>Form:</strong>
  <%= @architecture.form %>
</p>

<%= link_to 'Edit', edit_architecture_path(@architecture) %> |
<%= link_to 'Back', architectures_path %>