config/routes.rb
Rails.application.routes.draw do
  resources :architectures
  resources :deployments
  resources :load_balancers
  resources :servers
  resources :forms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'forms#new'
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:environment, :location, :purpose, :name, :accessibility, :description,
      servers_attributes: [:hostname, :ip, :os, :cpucores, :memory, :disk],
      load_balancers_attributes: [:lb_type, :ip_address, :server_type],
      deployments_attributes:[:repo, :stack, :software, :installation],
      architectures_attributes:[:description, :diagram_file_name, :diagram_content_type, :diagram_file_size, :diagram_updated_at])
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb

<%= form_for(form) do |f| %>
  <% if form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="jumbotron">
  <h1>Server Build Book</h1>
  <h6><strong>Purpose:</strong> The Server Build Book documentation is intended to provide Operations with an accurate account of all configurations modifications to get the server to its production state including any configuration modifications made as a result of vulnerability assessments and other security hardening efforts. Related relevant information pertaining to applications and databases hosted on these environments can be found in the companion Application Build Book.</h6>
</div>
<h3>General Info</h3>
<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row" class="row-description">Server Environment</th>
      <td>
        <%= f.label(:environment, 'Test') %>
        <%= f.radio_button(:environment, 'test') %>
        <%= f.label(:environment, 'Development') %>
        <%= f.radio_button(:environment, 'development') %>
        <%= f.label(:environment, 'Training') %>
        <%= f.radio_button(:environment, 'Training') %>
        <%= f.label(:environment, 'QA') %>
        <%= f.radio_button(:environment, 'qa') %>
        <%= f.label(:environment, 'Staging') %>
        <%= f.radio_button(:environment, 'staging') %>
        <%= f.label(:environment, 'Production') %>
        <%= f.radio_button(:environment, 'production') %>
      </td>
    </tr>

    <tr>
      <th scope="row" class="row-description">Server Location</th>
      <td><%= f.text_field(:location, class: "form-control") %></td>
    </tr>

    <tr>
      <th scope="row" class="row-description">Server Purpose</th>
      <td><%= f.text_area(:purpose, class: "form-control") %></td>
    </tr>

    <tr>
      <th scope="row" class="row-description">Application Name </th>
      <td><%= f.text_field(:name, class: "form-control") %></td>
    </tr>

    <tr>
      <th scope="row" class="row-description">Server Accessibility</th>
      <td>
        <%= f.label :accessibility,'Internal' %>
        <%= f.radio_button(:accessibility,'internal') %>
        <%= f.label :accessibility,'External' %>
        <%= f.radio_button(:accessibility,'external') %>
        <%= f.label :accessibility,'Both' %>
        <%= f.radio_button(:accessibility,'both') %>
      </td>
    </tr>

    <tr>
      <th scope="row" class="row-description">Application Description</th>
      <td><%= f.text_area(:description, class: "form-control") %></td>
    </tr>
  </tbody>
</table>

  <!-- section for servers -->
<h3>Server Info</h3>
<div>
  <table id="server-table" class="table table-bordered">
    <tr>
      <th class="row-description">Host Name</th>
      <th class="row-description">IP Address</th>
      <th class="row-description">Operating System</th>
      <th class="row-description">CPU Cores</th>
      <th class="row-description">Memory(GB)</th>
      <th class="row-description">Disk Space(GB)</th>
    </tr>

  <div id="server-row">
    <tr>
    <%= f.fields_for(:servers, Server.new, remote: true) do |server| %>
      <td><%= server.text_field :hostname, class: "form-control" %></td>
      <td><%= server.text_field :ip, class: "form-control" %></td>
      <td><%= server.select :os, options_for_select(["Ubuntu", "CentOS"], {class: "form-control"}) %></div>
      <td><%= server.number_field :cpucores, class: "form-control" %></td>
      <td><%= server.number_field :memory, class: "form-control" %></td>
      <td><%= server.number_field :disk, class: "form-control" %></td>
    <% end %>
    </tr>
  </div>
  </table>
  <td><button type="button" id="add-server" class="pull-right">Add Another Server!</button></td>
</div>
<div>
  <!-- section for load balancers -->
  <h3>Load Balancer Info</h3>
  <table id="load-balancer-table" class="table table-bordered">
  <tr>
    <th class="row-description">Type</th>
    <th class="row-description">IP Address</th>
    <th class="row-description">HTTP or APP</th>
  </tr>

  <div id="load-balancer-row" class="table table-boredered">
    <tr>
    <%= f.fields_for(:load_balancers, LoadBalancer.new, remote: true) do |balancer| %>
      <td><%= balancer.select :lb_type, options_for_select(["Kemp", "HA Proxy", "Zen"]) %></td>
      <td><%= balancer.text_field :ip_address, class: "form-control" %></td>
      <td><%= balancer.text_field :server_type, class: "form-control" %></td>
    <% end %>
    </tr>
  </table>
  <td><button type="button" id="add-load-balancer" class="pull-right">Add Load Balancer</button></td>
</div>

<!-- deployment information -->
<h3>Deployment Information</h3>
<table id="deployment-table" class="table table-bordered">
    <%= f.fields_for(:deployments, Deployment.new, remote: true) do |deployment| %>
    <tr>
      <th scope="row" class="row-description">GitHub Repo URL</th>
      <td><%= deployment.text_field(:repo, class: "form-control") %></td>
    </tr>
    <tr>
      <th scope="row" class="row-description">Application Stack</th>
      <td><%= deployment.text_field(:stack, class: "form-control") %></td>
    </tr>
    <tr>
      <th scope="row" class="row-description">Additional Software</th>
      <td><%= deployment.text_area(:software, class: "form-control") %></td>
    </tr>
    <tr>
      <th scope="row" class="row-description">Deployment Instructions</th>
      <td><%= deployment.text_area(:installation, class: "form-control") %></td>
    </tr>
    <% end %>
</table>

<!-- architecture information -->
<h3>Architecture Information</h3>
<table id="architecture-table" class="table table-bordered">
  <%= f.fields_for(:architectures, Architecture.new, remote: true) do |architecture| %>
  <tr>
    <th scope="row" class="row-description">Architecture Description</th>
    <td><%= architecture.text_area(:description, class: "form-control") %></td>
  </tr>
  <tr>
    <th scope="row" class="row-description">Upload Architecture</th>
    <td><%= f.file_field(:diagram, class: "btn btn-default btn-file", id: "pictureInput") %></td>
  <tr>
  <tr>
    <td id="target">
    </td>
  </tr>

  <% end %>
</table>


  <div class="actions">
    <%= f.submit %>
  </div>


<!-- JavaScript -->
  <script>
    $(document).ready(function(){
        var count = 1;
        $("#add-server").click(function(){
          $("#server-table").append('\
            <tbody> \
              <tr> \
                <td><input class="form-control" type="text" name="form[servers_attributes][' + count + '][hostname]" id="form_servers_attributes_' + count + '_hostname"></td> \
                <td><input class="form-control" type="text" name="form[servers_attributes][' + count + '][ip]" id="form_servers_attributes_' + count + '_ip"></td> \
                <td><select name="form[servers_attributes][' + count + '][os]" id="form_servers_attributes_' + count + '_os"><option value="Ubuntu">Ubuntu</option><option value="CentOS">CentOS</option></select></td> \
                <td><input class="form-control" type="number" name="form[servers_attributes][' + count + '][cpucores]" id="form_servers_attributes_' + count + '_cpucores"></td> \
                <td><input class="form-control" type="number" name="form[servers_attributes][' + count + '][memory]" id="form_servers_attributes_' + count + '_memory"></td> \
                <td><input class="form-control" type="number" name="form[servers_attributes][' + count + '][disk]" id="form_servers_attributes_' + count + '_disk"></td> \
              </tr > \
            </tbody> \
          ');
          count++;
        });
    });

    $(document).ready(function(){
        var count = 1;
        $("#add-load-balancer").click(function(){
          $("#load-balancer-table").append('\
            <tbody> \
              <tr> \
                <td><select name="form[load_balancers_attributes][' + count + '][lb_type]" id="form_load_balancers_attributes_' + count + '_lb_type"><option value="Kemp">Kemp</option><option value="HA Proxy">HA Proxy</option><option value="Zen">Zen</option></select></td> \
                <td><input class="form-control" type="text" name="form[load_balancers_attributes][' + count + '][ip_address]" id="form_load_balancers_attributes' + count + '_ip_address"></td> \
                <td><input class="form-control" type="text" name="form[load_balancers_attributes][' + count + '][server_type]" id="form_load_balancers_attributes_' + count + '_server_type"></td> \
              </tr > \
            </tbody> \
          ');
          count++;
        });
    });

    $(document).ready(function() {
      $('#pictureInput').on('change', function(event) {
        var files = event.target.files;
        var image = files[0]
        var reader = new FileReader();
        reader.onload = function(file) {
          var img = new Image();
          console.log(file);
          img.src = file.target.result;
          $('#target').html(img);
        }
        reader.readAsDataURL(image);
        console.log(files);
      });
    });
  </script>

<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forms</h1>

<table>
  <thead>
    <tr>
      <th>Environment</th>
      <th>Location</th>
      <th>Purpose</th>
      <th>Name</th>
      <th>Accessibility</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.environment %></td>
        <td><%= form.location %></td>
        <td><%= form.purpose %></td>
        <td><%= form.name %></td>
        <td><%= form.accessibility %></td>
        <td><%= form.description %></td>
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<center><h1>New Form</h1></center>

<div class="container">
    <%= render 'form', form: @form %>
</div>
<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Environment:</strong>
  <%= @form.environment %>
</p>

<p>
  <strong>Location:</strong>
  <%= @form.location %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @form.purpose %>
</p>

<p>
  <strong>Name:</strong>
  <%= @form.name %>
</p>

<p>
  <strong>Accessibility:</strong>
  <%= @form.accessibility %>
</p>

<p>
  <strong>Description:</strong>
  <%= @form.description %>
</p>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>