config/routes.rb
Rails.application.routes.draw do
  resources :architectures
  resources :deployments
  resources :load_balancers
  resources :servers
  resources :forms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'forms#new'
end

app/models/deployment.rb
class Deployment < ApplicationRecord
  belongs_to(:form, required: false)
end

app/controllers/deployments_controller.rb
class DeploymentsController < ApplicationController
  before_action :set_deployment, only: [:show, :edit, :update, :destroy]

  # GET /deployments
  # GET /deployments.json
  def index
    @deployments = Deployment.all
  end

  # GET /deployments/1
  # GET /deployments/1.json
  def show
  end

  # GET /deployments/new
  def new
    @deployment = Deployment.new
  end

  # GET /deployments/1/edit
  def edit
  end

  # POST /deployments
  # POST /deployments.json
  def create
    @deployment = Deployment.new(deployment_params)

    respond_to do |format|
      if @deployment.save
        format.html { redirect_to @deployment, notice: 'Deployment was successfully created.' }
        format.json { render :show, status: :created, location: @deployment }
      else
        format.html { render :new }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deployments/1
  # PATCH/PUT /deployments/1.json
  def update
    respond_to do |format|
      if @deployment.update(deployment_params)
        format.html { redirect_to @deployment, notice: 'Deployment was successfully updated.' }
        format.json { render :show, status: :ok, location: @deployment }
      else
        format.html { render :edit }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deployments/1
  # DELETE /deployments/1.json
  def destroy
    @deployment.destroy
    respond_to do |format|
      format.html { redirect_to deployments_url, notice: 'Deployment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deployment
      @deployment = Deployment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deployment_params
      params.require(:deployment).permit(:repo, :stack, :software, :installation, :form_id)
    end
end

app/helpers/deployments_helper.rb
module DeploymentsHelper
end

app/views/deployments/_form.html.erb
<%= form_for(deployment) do |f| %>
  <% if deployment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deployment.errors.count, "error") %> prohibited this deployment from being saved:</h2>

      <ul>
      <% deployment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :repo %>
    <%= f.text_field :repo %>
  </div>

  <div class="field">
    <%= f.label :stack %>
    <%= f.text_field :stack %>
  </div>

  <div class="field">
    <%= f.label :software %>
    <%= f.text_area :software %>
  </div>

  <div class="field">
    <%= f.label :installation %>
    <%= f.text_area :installation %>
  </div>

  <div class="field">
    <%= f.label :form_id %>
    <%= f.text_field :form_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deployments/edit.html.erb
<h1>Editing Deployment</h1>

<%= render 'form', deployment: @deployment %>

<%= link_to 'Show', @deployment %> |
<%= link_to 'Back', deployments_path %>

app/views/deployments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deployments</h1>

<table>
  <thead>
    <tr>
      <th>Repo</th>
      <th>Stack</th>
      <th>Software</th>
      <th>Installation</th>
      <th>Form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deployments.each do |deployment| %>
      <tr>
        <td><%= deployment.repo %></td>
        <td><%= deployment.stack %></td>
        <td><%= deployment.software %></td>
        <td><%= deployment.installation %></td>
        <td><%= deployment.form %></td>
        <td><%= link_to 'Show', deployment %></td>
        <td><%= link_to 'Edit', edit_deployment_path(deployment) %></td>
        <td><%= link_to 'Destroy', deployment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deployment', new_deployment_path %>

app/views/deployments/new.html.erb
<h1>New Deployment</h1>

<%= render 'form', deployment: @deployment %>

<%= link_to 'Back', deployments_path %>

app/views/deployments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Repo:</strong>
  <%= @deployment.repo %>
</p>

<p>
  <strong>Stack:</strong>
  <%= @deployment.stack %>
</p>

<p>
  <strong>Software:</strong>
  <%= @deployment.software %>
</p>

<p>
  <strong>Installation:</strong>
  <%= @deployment.installation %>
</p>

<p>
  <strong>Form:</strong>
  <%= @deployment.form %>
</p>

<%= link_to 'Edit', edit_deployment_path(@deployment) %> |
<%= link_to 'Back', deployments_path %>