config/routes.rb
Rails.application.routes.draw do
  resources :architectures
  resources :deployments
  resources :load_balancers
  resources :servers
  resources :forms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'forms#new'
end

app/models/load_balancer.rb
class LoadBalancer < ApplicationRecord
  belongs_to(:form, required: false)
end

app/controllers/load_balancers_controller.rb
class LoadBalancersController < ApplicationController
  before_action :set_load_balancer, only: [:show, :edit, :update, :destroy]

  # GET /load_balancers
  # GET /load_balancers.json
  def index
    @load_balancers = LoadBalancer.all
  end

  # GET /load_balancers/1
  # GET /load_balancers/1.json
  def show
  end

  # GET /load_balancers/new
  def new
    @load_balancer = LoadBalancer.new
  end

  # GET /load_balancers/1/edit
  def edit
  end

  # POST /load_balancers
  # POST /load_balancers.json
  def create
    @load_balancer = LoadBalancer.new(load_balancer_params)

    respond_to do |format|
      if @load_balancer.save
        format.html { redirect_to @load_balancer, notice: 'Load balancer was successfully created.' }
        format.json { render :show, status: :created, location: @load_balancer }
      else
        format.html { render :new }
        format.json { render json: @load_balancer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /load_balancers/1
  # PATCH/PUT /load_balancers/1.json
  def update
    respond_to do |format|
      if @load_balancer.update(load_balancer_params)
        format.html { redirect_to @load_balancer, notice: 'Load balancer was successfully updated.' }
        format.json { render :show, status: :ok, location: @load_balancer }
      else
        format.html { render :edit }
        format.json { render json: @load_balancer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /load_balancers/1
  # DELETE /load_balancers/1.json
  def destroy
    @load_balancer.destroy
    respond_to do |format|
      format.html { redirect_to load_balancers_url, notice: 'Load balancer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_load_balancer
      @load_balancer = LoadBalancer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def load_balancer_params
      params.require(:load_balancer).permit(:type, :ip_addres, :server_type, :form_id)
    end
end

app/helpers/load_balancers_helper.rb
module LoadBalancersHelper
end

app/views/load_balancers/_form.html.erb
<%= form_for(load_balancer) do |f| %>
  <% if load_balancer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(load_balancer.errors.count, "error") %> prohibited this load_balancer from being saved:</h2>

      <ul>
      <% load_balancer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lb_type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :ip_address %>
    <%= f.text_field :ip_address %>
  </div>

  <div class="field">
    <%= f.label :server_type %>
    <%= f.text_field :server_type %>
  </div>

  <div class="field">
    <%= f.label :form_id %>
    <%= f.text_field :form_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/load_balancers/edit.html.erb
<h1>Editing Load Balancer</h1>

<%= render 'form', load_balancer: @load_balancer %>

<%= link_to 'Show', @load_balancer %> |
<%= link_to 'Back', load_balancers_path %>

app/views/load_balancers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Load Balancers</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Ip addres</th>
      <th>Server type</th>
      <th>Form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @load_balancers.each do |load_balancer| %>
      <tr>
        <td><%= load_balancer.lb_type %></td>
        <td><%= load_balancer.ip_address%></td>
        <td><%= load_balancer.server_type %></td>
        <td><%= load_balancer.form %></td>
        <td><%= link_to 'Show', load_balancer %></td>
        <td><%= link_to 'Edit', edit_load_balancer_path(load_balancer) %></td>
        <td><%= link_to 'Destroy', load_balancer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Load Balancer', new_load_balancer_path %>

app/views/load_balancers/new.html.erb
<h1>New Load Balancer</h1>

<%= render 'form', load_balancer: @load_balancer %>

<%= link_to 'Back', load_balancers_path %>

app/views/load_balancers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @load_balancer.lb_type %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @load_balancer.ip_address%>
</p>

<p>
  <strong>Server type:</strong>
  <%= @load_balancer.server_type %>
</p>

<p>
  <strong>Form:</strong>
  <%= @load_balancer.form %>
</p>

<%= link_to 'Edit', edit_load_balancer_path(@load_balancer) %> |
<%= link_to 'Back', load_balancers_path %>